name = "notarium-backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "notarium-db"
database_id = "17779d22-7479-479c-8de7-dfe102916ba3"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder_create_kv_namespace"

[env.development]
vars = { ENVIRONMENT = "development", FRONTEND_URL = "http://localhost:5173" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "notarium-db-local"
database_id = "local-dev"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder_create_kv_namespace"
preview_id = "placeholder_create_kv_namespace"

[env.production]
vars = { ENVIRONMENT = "production", FRONTEND_URL = "https://notarium-site.vercel.app" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "notarium-db"
database_id = "17779d22-7479-479c-8de7-dfe102916ba3"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder_create_kv_namespace"
